/*
 * User Services Platform - Controller API
 *
 * This is the REST API for the User Services Platform (USP) Controller.  This is how an external entity can interact with a USP Controller to retrieve information from or configure a USP Agent.
 *
 * API version: 1.0.0
 * Contact: info@broadband-forum.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v2/",
		Index,
	},

	Route{
		"CreateAgent",
		strings.ToUpper("Post"),
		"/v2/agents",
		CreateAgent,
	},

	Route{
		"CreateAgentServiceElement",
		strings.ToUpper("Post"),
		"/v2/agents/{endpointID}/serviceElements",
		CreateAgentServiceElement,
	},

	Route{
		"DeleteAgent",
		strings.ToUpper("Delete"),
		"/v2/agents/{endpointID}",
		DeleteAgent,
	},

	Route{
		"DeleteAgentServiceElement",
		strings.ToUpper("Delete"),
		"/v2/agents/{endpointID}/serviceElements/{name}",
		DeleteAgentServiceElement,
	},

	Route{
		"ExecuteAgentServiceElementAction",
		strings.ToUpper("Post"),
		"/v2/agents/{endpointID}/commands",
		ExecuteAgentServiceElementAction,
	},

	Route{
		"GetAgentDetails",
		strings.ToUpper("Get"),
		"/v2/agents/{endpointID}",
		GetAgentDetails,
	},

	Route{
		"GetAgentServiceElement",
		strings.ToUpper("Get"),
		"/v2/agents/{endpointID}/serviceElements/{name}",
		GetAgentServiceElement,
	},

	Route{
		"GetAgentServiceElementActionResults",
		strings.ToUpper("Get"),
		"/v2/agents/{endpointID}/commands/{asyncRequestID}",
		GetAgentServiceElementActionResults,
	},

	Route{
		"GetAgentStatus",
		strings.ToUpper("Get"),
		"/v2/agents/{endpointID}/status",
		GetAgentStatus,
	},

	Route{
		"SearchAgents",
		strings.ToUpper("Get"),
		"/v2/agents/{endpointID}/associatedAgents",
		SearchAgents,
	},

	Route{
		"UpdateAgent",
		strings.ToUpper("Put"),
		"/v2/agents/{endpointID}",
		UpdateAgent,
	},

	Route{
		"UpdateAgentServiceElements",
		strings.ToUpper("Patch"),
		"/v2/agents/{endpointID}/serviceElements/{name}",
		UpdateAgentServiceElements,
	},
}
